// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1pkP_KEJr7KEFx8zLrRiW6k7HWrlQyE',
    appId: '1:183581153519:web:a595ba99d710ff4d9be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    authDomain: 'tracking-app-a9e77.firebaseapp.com',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    measurementId: 'G-EXGRTBLSCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfAE__1dHLsY6Wr_mGx-BBNE0KJpbO6c',
    appId: '1:183581153519:android:3606936c48ee4bf69be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG1pkP_KEJr7KEFx8zLrRiW6k7HWrlQyE',
    appId: '1:183581153519:web:c09b810e608c9f009be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    authDomain: 'tracking-app-a9e77.firebaseapp.com',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    measurementId: 'G-NG7NXD6CCE',
  );
}
